# Generated by Django 3.1.3 on 2023-08-14 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20230814_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='choice_List',
        ),
    ]
