# Generated by Django 3.1.3 on 2023-08-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_remove_submission_choice_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission_chocies',
            name='choice_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
