# Generated by Django 3.1.3 on 2023-08-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0004_auto_20230814_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission_chocies',
            name='answerPool',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.RemoveField(
            model_name='submission_chocies',
            name='choice_id',
        ),
        migrations.AddField(
            model_name='submission_chocies',
            name='choice_id',
            field=models.ManyToManyField(to='onlinecourse.Choice'),
        ),
    ]
